- name: Install cli apps
  hosts: localhost
  tasks:
    - name: Updating apt repos
      become: true
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Installing cli packages
      become: true
      ansible.builtin.apt:
        pkg:
          - zsh
          - git
          - curl
          - git-lfs
          - wget
          - stow
          - ripgrep
          - fzf
          - tmux
          - neovim
        state: latest

    - name: Making zsh default
      become: true
      user:
        name: "{{ansible_user_id}}"
        shell: /usr/bin/zsh

    - name: Checking if Oh-my-zsh is installed
      ansible.builtin.stat:
        path: ~/.oh-my-zsh
      register: ohmyzsh

    - name: Removing Oh-my-zsh
      ansible.builtin.shell: rm -rf {{ohmyzsh.stat.path}}
      when: ohmyzsh.stat.exists

    - name: Setting up Oh-my-zsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" > /dev/null

    - name: Installing nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | zsh
      args:
        executable: /usr/bin/zsh
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Installing node & npm
      ansible.builtin.shell: |
        source ~/.nvm/nvm.sh && nvm install --lts && nvm alias default node
      args:
        executable: /usr/bin/zsh
        chdir: "$HOME"

    - name: Installing zsh-autosuggestions
      ansible.builtin.git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions

    - name: Setting up dotfiles
      ansible.builtin.git:
        repo: https://github.com/cokoghenun/.dotfiles.git
        dest: ~/.dotfiles

    - name: Preparing folders
      ansible.builtin.shell: rm -rf ~/.zshrc ~/.tmux.conf ~/.gitconfig ~/.config/nvim

    - name: Installing dotfiles
      ansible.builtin.command: stow .
      args:
        chdir: ~/.dotfiles

    - name: Installing packer
      ansible.builtin.git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
        depth: 1

    - name: Installing nvim plugins
      ansible.builtin.shell: nvim --headless -c 'so ~/.dotfiles/.config/nvim/lua/config/packer.lua' -c PackerSync +q

    - name: Installing tpm and tmux plugins
      ansible.builtin.shell: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins

    - name: Installing docker & docker compose
      ansible.builtin.shell: curl -fsSL get.docker.com | sh

    - name: Setting up sudoless docker permissions
      ansible.builtin.shell: usermod -aG docker $USER && newgrp docker
      become: true
