- name: Install neovim
  hosts: localhost
  tasks:
    - name: Updating apt repos
      become: true
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
          
    - name: Uninstalling apt neovim
      become: true
      ansible.builtin.apt:
        name: neovim
        state: absent

    - name: Installing dependencies
      become: true
      ansible.builtin.apt:
        pkg:
          - ninja-build
          - gettext 
          - libtool 
          - libtool-bin 
          - autoconf 
          - automake 
          - cmake
          - g++ 
          - pkg-config 
          - unzip 
          - curl 
          - doxygen
        state: latest

    - name: Cloning repo
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim.git
        dest: ~/neovim/

    - name: Building neovim
      ansible.builtin.shell: make CMAKE_BUILD_TYPE=Release
      args:
        chdir: ~/neovim/

    - name: Installing neovim
      ansible.builtin.shell: make install
      become: true
      args:
        chdir: /home/megaconfidence/neovim/
        
    - name: Installing neovim plugins
      ansible.builtin.shell: nvim --headless -c 'so ~/.dotfiles/.config/nvim/lua/config/packer.lua' -c PackerSync +q
      # ansible.builtin.shell: nvim --headless +'so ~/.dotfiles/.config/nvim/lua/config/packer.lua' +PackerInstall +q
